local_backend: true

backend:
  name: git-gateway

media_folder: "public/images/uploads"

public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "pubDate", label: "Publish Date", widget: "datetime", format: "YYYY-MM-DD" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "author", label: "Author", widget: "string" }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
          - { name: "url", label: "Image URL", widget: "image" }
          - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list", default: ["general"] }
      - { name: "body", label: "Post Body", widget: "markdown" }
